### ISSUE TITLE
安装时遇到的关于openssh的问题与找到的解决方式

### ISSUE THREAD

**Issue by YuanNing-96** [iTXTech/mcl-installer#1]
萌新在安装时遇到的一个小问题及解决方案
在 cargo build --release这一步，看着好像是找不到openssh-0.8几的一个报错，大概在进度条90多/125的时候
（前提是已经安装了openssh）
解决一:按提示安装了pkg-config，我安装后问题好像变了，但还是这里有问题
解决二：sudo apt-get install libssl-dev，网上说是linux系统没有默认安装这个包，但是这个包是openssh的一部分，所以需要按上。
这两步搞定后，这个问题就解决了 (虽然还有10个warning等着我)

**Comment by PeratX** [comment]
一般来说，直接下载releases中构建好的可执行文件就行了，请问您是什么平台？
Linux系统依赖OpenSSL，需要安装开发包才能编译。macOS和Windows直接调用系统的SSL。
warning正常的，我懒得优雅了。

**Comment by PeratX** [comment]
`cargo build --features rustls --release` 即可不需要任何依赖即可编译。
