### ISSUE TITLE
mcl-installer-72b890d-windows-amd64.exe - 系统错误

### ISSUE THREAD

**Issue by mimicode** [iTXTech/mcl-installer#13]
---------------------------
mcl-installer-72b890d-windows-amd64.exe - 系统错误
---------------------------
无法启动此程序，因为计算机中丢失 api-ms-win-crt-heap-l1-1-0.dll。尝试重新安装该程序以解决此问题。 
---------------------------
确定   
---------------------------

**Comment by PeratX** [comment]
尝试安装VC++ 2019 可再发行组件包
