### ISSUE TITLE
建议换源或提供选源

### ISSUE THREAD

**Issue by Initial-heart-1** [iTXTech/mcl-installer#14]
如github与gitee，清华源和USTC，比如我这里清华源非常慢，USTC就可以跑满带宽
可以有效改善下载体验，而且也不费事
能力有限交不了PR 只能提个建议了

**Comment by PeratX** [comment]
国内提供AdoptOpenJDK镜像的只有清华源

**Comment by Initial-heart-1** [comment]
得嘞，这就问问

**Comment by Initial-heart-1** [comment]
> 国内提供AdoptOpenJDK镜像的只有清华源

https://mirrors.ustc.edu.cn/github-release/AdoptOpenJDK/

**Comment by PeratX** [comment]
两个源的目录结构不一样，要开发两套方案

**Comment by Initial-heart-1** [comment]
> 两个源的目录结构不一样，要开发两套方案

都好说，目录结构不是大问题

**Comment by Initial-heart-1** [comment]
主要是不懂rust，不然我直接交PR了，还搁这开issues呢

**Comment by PeratX** [comment]
有点道理，有空看下

**Comment by PeratX** [comment]
已支持自定义mirai repo源
