### ISSUE TITLE
Ubuntu20.04-arm64运行新的版本会出现“Segmentation fault”错误

### ISSUE THREAD

**Issue by Kaleidoscope39** [iTXTech/mcl-installer#16]
设备是斐讯N1。
这个问题可能也在其他的actions编译出来的linux-aarch64执行文件中存在。

> root@server:~# ./mcl-installer-72b890d-linux-aarch64
> Segmentation fault

> root@server:~# uname -a
> Linux server 5.12.6-aml-s905d-starx-action #1 SMP PREEMPT Sun May 23 13:15:33 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

**Comment by Feiyuyu0503** [comment]
也出现了这个问题
```
ubuntu@instance-20210528-1836:~/QQBot/mirai$ ./mcl-installer-72b890d-linux-aarch64
Segmentation fault (core dumped)
ubuntu@instance-20210528-1836:~/QQBot/mirai$ uname -a
Linux instance-20210528-1836 5.4.0-1045-oracle #49-Ubuntu SMP Mon May 3 05:27:18 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by PeratX** [comment]
可能还是工具链问题，小众平台无法一一测试
有条件请测试一下本地编译?

**Comment by Kaleidoscope39** [comment]
新版本（1.0.3）已经修复此问题
