### ISSUE TITLE
v1.0.3版本无法下载 edge和腾讯云报毒

### ISSUE THREAD

**Issue by YuzeTT** [iTXTech/mcl-installer#23]
edge和chrome均无法下载
![image](https://user-images.githubusercontent.com/61106448/134032572-e05ae783-6353-49d5-a656-4fb3ac3a9ab5.png)

尝试使用Linux云服务器下载后传输 无法运行
![image](https://user-images.githubusercontent.com/61106448/134032746-e96127de-9810-4526-a28e-c8b409dc57fb.png)

收到腾讯云报毒邮件
![image](https://user-images.githubusercontent.com/61106448/134032787-7dbefa2e-bd4b-4e84-82db-3af720df5074.png)

**Comment by PeratX** [comment]
请自行解决。
