### ISSUE TITLE
运行installer时报错

### ISSUE THREAD

**Issue by da-qing-wa** [iTXTech/mcl-installer#25]
./mcl-installer-1.0.3-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./mcl-installer-1.0.3-linux-amd64)

**Comment by m00nfly** [comment]
linux 操作系统版本太旧了，系统的 glibc 依赖库版本太低，
要么自己手动编译 2.18 版本的glibc 替换系统默认的 libc库；
要么换新一点的Linux 系统发行版；

**Comment by PeratX** [comment]
楼上正解，预编译的版本要求比较新，不然需要手动编译
