### ISSUE TITLE
illegal instruction错误

### ISSUE THREAD

**Issue by HelloGwkki** [iTXTech/mcl-installer#3]
我正在Redmi Note 5A上使用termux，用atilo及proot安装了Ubuntu，下载了mcl installer amd64版本，运行时出现了illegal instruction错误。

**Comment by PeratX** [comment]
必然的，没猜错手机上aarch64，不是amd64
您可以手动安装mcl，ubuntu可使用apt安装openjdk11，然后再从mcl的releases下载压缩包解压即可使用。
若要使用mcl-installer，您需要手动从源码构建，并且不保证下载的aarch64的jdk能正常运行
