### ISSUE TITLE
mcl-installer-1.0.3-android-aarch64启动报错：Segmentation fault

### ISSUE THREAD

**Issue by lincannm** [iTXTech/mcl-installer#31]
mcl installer版本是目前最新版1.0.3
使用ZeroTermux直接启动：
![IMG_20220214_181654](https://user-images.githubusercontent.com/41236336/153850579-dceb6051-879f-4eb2-8fe7-5ab9cecb7d23.jpg)
然而mcl-installer-1.0.3-android-arm启动就没有问题：
![IMG_20220214_185600](https://user-images.githubusercontent.com/41236336/153851105-267d552d-84ed-461a-b5e7-accad73e58a2.jpg)
我的安卓手机架构是aarch64，貌似用aarch64版本更合理一些吧😂

**Comment by PeratX** [comment]
~~能用就行~~

**Comment by lincannm** [comment]
不过使用mcl-installer-1.0.3-android-arm安装java之后就报错停止了
![Screenshot_2022-02-14-18-57-54-474_com termux](https://user-images.githubusercontent.com/41236336/153851771-4a9f12eb-090c-46c3-84b0-4ee0a49d2547.jpg)

**Comment by lincannm** [comment]
> ~能用就行~

然而不能用（

**Comment by lincannm** [comment]
mcl-installer-1.0.3-linux-aarch64的话反倒没反应了，也许得开linux容器了
![IMG_20220214_190350](https://user-images.githubusercontent.com/41236336/153852448-2fc8a46b-5a92-46a0-8e4b-e99a73dcb517.jpg)

**Comment by lincannm** [comment]
使用[tmoe脚本](http://git.oschina.net/mo2/linux)装了ubuntu容器总算可以了
![IMG_20220214_222706](https://user-images.githubusercontent.com/41236336/153882567-97897528-4d45-482f-a4db-3eea57aabd64.jpg)
只是每次都要开容器才能启动mcl，最好适配一下安卓吧π_π

**Comment by PeratX** [comment]
其实有点困难，我这边没有Android设备

**Comment by lincannm** [comment]
> 其实有点困难，我这边没有Android设备

没事，哪天有条件了适配一下，目前至少能用
![5d1424da81af09e8](https://user-images.githubusercontent.com/41236336/154810393-e5adb5e8-95d7-4849-bd22-9ee16eec2f21.png)

**Comment by PeratX** [comment]
合并到 #17
