### ISSUE TITLE
releases下载不了

### ISSUE THREAD

**Issue by xxj7527** [iTXTech/mcl-installer#37]
1.release前两个项目所有文件都404

2.可以下载1.06。Linux用readme的示例一键安装提示缺少文件：

> cd /mirai
curl -LJO https://github.com/iTXTech/mcl-installer/releases/download/v1.0.6/mcl-installer-1.0.6-linux-amd64 
>chmod +x mcl-installer-1.0.6-linux-amd64
> ./mcl-installer-1.0.6-linux-amd64

报错：

> ./mcl-installer-1.0.6-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by ./mcl-installer-1.0.6-linux-amd64)

> ./mcl-installer-1.0.6-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./mcl-installer-1.0.6-linux-amd64)

> ./mcl-installer-1.0.6-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./mcl-installer-1.0.6-linux-amd64)

> ./mcl-installer-1.0.6-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./mcl-installer-1.0.6-linux-amd64)

**Comment by PeratX** [comment]
请尝试 
https://github.com/iTXTech/mcl-installer/releases/download/d5a51f8/mcl-installer-d5a51f8-linux-amd64-musl

**Comment by xxj7527** [comment]
> 请尝试 https://github.com/iTXTech/mcl-installer/releases/download/d5a51f8/mcl-installer-d5a51f8-linux-amd64-musl


可以了 真奇怪 试了一个通宵前两个release都不行 又试了一上午1 06所有包 也不行 到处找问题，突然发现前两个release变成404 这会又能下载了 搞得我现在能用但是还是不知道问题出在哪里...

对了哥现在这个还需要手动修改mirai_repo地址吗

**Comment by PeratX** [comment]
下载404应该是GitHub的问题，您昨天提出问题的时候我也是404，过了一会就又可以了。
有的linux系统的glibc版本比较老旧，所以不支持使用linux-amd64的包，所以我新设了linux-amd64-musl，其没有外部依赖，兼容性更好。
