### ISSUE TITLE
W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用

### ISSUE THREAD

**Issue by yuanbolin** [iTXTech/mcl-installer#39]
启动mcl时提示:W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用

**Comment by PeratX** [comment]
这是来自mcl-addon的提示
Soyuz是向 mirai-webui 提供 WebSocket接口的服务端
MCL Addon实现了部分接口用以对接webui，如果您不需要使用该功能，请忽略。

更多信息详见：
https://github.com/iTXTech/soyuz
https://github.com/iTXTech/mcl-addon
