### ISSUE TITLE
aarch64 termux运行segmentation fault

### ISSUE THREAD

**Issue by EricTianC** [iTXTech/mcl-installer#4]
mcl-installer-afdc1a0-android-aarch64  
Xiaomi 10 pro      Termux

**Comment by PeratX** [comment]
没有真机进行测试，请尝试从源码构建
`cargo build --features rustls --release`

此外，Termux无法运行AdoptOpenJDK，可能先要在termux里安装ubuntu才行

**Comment by fatinghenji** [comment]
termux里面运行aarch64报错，但是运行arm可以跑起来
`此外，Termux无法运行AdoptOpenJDK，可能先要在termux里安装ubuntu才行`
termux官方支持java环境了，使用`pkg install openjdk-17`安装
