### ISSUE TITLE
Mac下执行安装mus文件报错

### ISSUE THREAD

**Issue by FarAwaytarget** [iTXTech/mcl-installer#41]
你好，根据指引操作执行 
./mcl-installer-1.0.7-macos-amd64-musl  提示./mcl-installer-1.0.7-macos-amd64-musl: line 1: Not: command not found
环境变量应该没问题。。比较小白大佬能帮忙看看哪里的问题吗，谢谢。

**Comment by PeratX** [comment]
系统版本？CPU型号？

**Comment by FarAwaytarget** [comment]
mac 解决了。linux不行了，增加执行权限后，再执行提示未找到命令

Linux VM-0-13-centos 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
./mcl-installer-1.0.7-linux-amd64-musl:行1: Not: 未找到命令

**Comment by PeratX** [comment]
请确保文件内容无误
使用 file命令查看文件类型，使用sha1sum等命令校验，请尝试再次下载
高度怀疑你这个文件的内容是Not Found，你可以cat一下看看
