### ISSUE TITLE
每次运行./mcl指令之后config里面的配置文件都会重置

### ISSUE THREAD

**Issue by Q2297045667** [iTXTech/mcl-installer#45]
安装完程序和插件之后
每次运行./mcl指令之后config里面的配置文件都会重置
每次都要配置一遍配置文件
还是说我的启动方式不对？

**Comment by PeratX** [comment]
是否有手动修改配置文件？若有手动修改请确保语法正确。
进一步问题请直接向mirai项目反馈，mcl不负责配置文件部分
