### ISSUE TITLE
(https://mirrors.tuna.tsinghua.edu.cn/Adoptium/18/jdk/x64/linux/): error trying to connect: tcp connect error: Operation timed out (os error 110)

### ISSUE THREAD

**Issue by mobilelifeful** [iTXTech/mcl-installer#48]
root@1add90:~# chmod +x mcl-installer-1.0.7-linux-amd64-musl
root@1add90:~# ./mcl-installer-1.0.7-linux-amd64-musl 
iTXTech MCL Installer 1.0.7 [OS: linux]
Licensed under GNU AGPLv3.
https://github.com/iTXTech/mcl-installer

iTXTech MCL and Java will be downloaded to "/root"

Checking existing Java installation.
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb11u1, mixed mode, sharing)

Would you like to install Java? (Y/N, default: Y) y
Java version (8, 11, 17, 18), default: 17): 18
JRE or JDK (1: JRE, 2: JDK, default: JRE): 2
Binary Architecture (default: x64): 
Fetching file list for jdk version 18 on x64 from https://mirrors.tuna.tsinghua.edu.cn/Adoptium/18/jdk/x64/linux/
[src/main.rs:239:14] Fail to fetch AdoptOpenJDK download list: error sending request for url (https://mirrors.tuna.tsinghua.edu.cn/Adoptium/18/jdk/x64/linux/): error trying to connect: tcp connect error: Operation timed out (os error 110)

**Comment by PeratX** [comment]
请检查网络连接，暂不支持更换jdk镜像
