### ISSUE TITLE
新安装的问题：[ERROR] java.util.zip.ZipException: invalid END header

### ISSUE THREAD

**Issue by HayatoOvO** [iTXTech/mcl-installer#52]
这是我新安装的 不知道出了什么问题 安装过程就都是默认 我连字都没打（悲
![image](https://user-images.githubusercontent.com/79782919/209164427-0056c35a-51c3-4a75-b9a8-a176a74a6ee0.png)

**Comment by PeratX** [comment]
网不好导致下载下来的文件损坏了
