### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:139:54

### ISSUE THREAD

**Issue by shirakun** [iTXTech/mcl-installer#8]
OS: ubuntu-18.04-x86_64

```
root@localhost:~# ./mcl-installer-1.0.2-linux-amd64
iTXTech MCL Installer 1.0.2 [OS: linux]
Licensed under GNU AGPLv3.
https://github.com/iTXTech/mcl-installer

iTXTech MCL and Java will be downloaded to "/root"

Checking existing Java installation.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:139:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

**Comment by PeratX** [comment]
请尝试使用最新版
https://github.com/iTXTech/mcl-installer/releases/tag/2827601

**Comment by b9891796435** [comment]
OS:CentOS 7.8 64位，出现了完全相同的报错，已经使用连接所指向版本

**Comment by PeratX** [comment]
请提交错误报告

**Comment by b9891796435** [comment]
[root@VM-0-14-centos iTXTech-MCL]# ./mcl-installer-1.0.2-linux-amd64
iTXTech MCL Installer 1.0.2 [OS: linux]
Licensed under GNU AGPLv3.
https://github.com/iTXTech/mcl-installer

iTXTech MCL and Java will be downloaded to "/usr/local/iTXTech-MCL"

Checking existing Java installation.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:139:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
