### ISSUE TITLE
在服务器上构建失败

### ISSUE THREAD

**Issue by MoonShadowIllusion** [iTXTech/mcl-installer#9]
error: could not compile `mcl-installer`.

Caused by:
  process didn't exit successfully: `rustc --crate-name mcl_installer --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=z -C panic=abort -C lto -C codegen-units=1 --cfg 'feature="native-tls"' -C metadata=f6eeeadc2996a42c -C extra-filename=-f6eeeadc2996a42c --out-dir /opt/mcl/mcl-installer-master/target/release/deps -L dependency=/opt/mcl/mcl-installer-master/target/release/deps --extern reqwest=/opt/mcl/mcl-installer-master/target/release/deps/libreqwest-9422b81f1bfe3e57.rlib --extern serde=/opt/mcl/mcl-installer-master/target/release/deps/libserde-43ddf14b67b9763b.rlib --extern tokio=/opt/mcl/mcl-installer-master/target/release/deps/libtokio-930bfbe0a9ad277e.rlib --extern zip=/opt/mcl/mcl-installer-master/target/release/deps/libzip-5a462b28bbc0e597.rlib` (signal: 9, SIGKILL: kill)

root@xuke:/opt/mcl# uname -a
Linux xuke 4.15.0-137-generic #141-Ubuntu SMP Fri Feb 19 13:47:36 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

**Comment by PeratX** [comment]
请使用rustls尝试
